apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-dpl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: prod
  template:
    metadata:
      name: prod-pod
      labels:
        # Champ non impose
        app: prod
    spec:
      containers:
      - name: prod
        image: apalpant/python-tp-k8s:1.0
# Saut de configuration
---

apiVersion: v1
kind: Service
metadata:
  name: prod-srv
spec:
  type: NodePort
  selector:
    # Correspond au label dans le prod-pod/labels
    app: prod
  ports:
      - port: 3400    # accessibilité de ce service depuis l'intérieur du cluster
        targetPort: 5000    # cible l'application serveur containerisé dans le pod referencé par ce selector
        nodePort: 30009   # accessibilité pour l'accès depuis l'extérieur du cluster