apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dpl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: test
  template:
    metadata:
      name: test-pod
      labels:
        # Champ non impose
        app: test
    spec:
      containers:
      - name: test
        image: apalpant/python-tp-k8s:1.0
# Saut de configuration
---

apiVersion: v1
kind: Service
metadata:
  name: test-srv
spec:
  type: NodePort
  selector:
    # Correspond au label dans le test-pod/labels
    app: test
  ports:
      - port: 3300    # accessibilité de ce service depuis l'intérieur du cluster
        targetPort: 5000    # cible l'application serveur containerisé dans le pod referencé par ce selector
        nodePort: 30008   # accessibilité pour l'accès depuis l'extérieur du cluster